services:
  memtier_benchmark:
    build: .
    command: --server=redis --generate-keys
    depends_on:
      - redis
    mem_limit: ${BENCHMARK_MEMORY_LIMIT:-256M}
    cpuset: ${CPUSET:-0}

  redis:
    image: redis
    command: --maxmemory ${REDIS_MAXMEMORY:-64mb}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    mem_limit: ${REDIS_MEMORY_LIMIT:-128M}
    cpuset: ${CPUSET:-0}


